    MACHINE-LEARNING-DEPLOYMENT-PHASE

#### **Deployment Phase**
```yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ml-app .

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag ml-app:latest <your-docker-repo>/ml-app:latest
          docker push <your-docker-repo>/ml-app:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          ```

---

## **6. Resources**
1. **Snyk**: [Snyk Documentation](https://snyk.io/docs/)
2. **Gradio**: [Gradio Documentation](https://gradio.app/)
3. **Streamlit Cloud**: [Streamlit Cloud](https://strea
